"""hard delete accounts

Revision ID: 1b08786564b8
Revises: 0d351d29060a
Create Date: 2026-09-29 15:35:36.027047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b08786564b8'
down_revision: Union[str, Sequence[str], None] = '0d351d29060a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='user_status_enum',
        new_values=['active', 'banned'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='status', existing_server_default="'active'::user_status_enum")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='user_status_enum',
        new_values=['active', 'banned', 'deleted'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='status', existing_server_default="'active'::user_status_enum")],
        enum_values_to_rename=[],
    )
    op.add_column('users', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
