"""add subscriptions

Revision ID: 06d99bd5dd7c
Revises: 1af132892dbc
Create Date: 2026-09-29 16:25:32.855362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06d99bd5dd7c'
down_revision: Union[str, Sequence[str], None] = '1af132892dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('free', 'premium', name='plan_code_enum').create(op.get_bind())
    op.create_table('subscriptions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('plan', postgresql.ENUM('free', 'premium', name='plan_code_enum', create_type=False), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("plan != 'free'", name=op.f('ck_subscriptions_paid_plan_only')),
    sa.CheckConstraint('expires_at > starts_at', name=op.f('ck_subscriptions_expires_after_start')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_user_id_expires_at'), 'subscriptions', ['user_id', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id_expires_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    sa.Enum('free', 'premium', name='plan_code_enum').drop(op.get_bind())
    # ### end Alembic commands ###
