"""create initial schema

Revision ID: 0d351d29060a
Revises: 
Create Date: 2026-09-29 15:26:17.036716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0d351d29060a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('status', sa.Enum('active', 'banned', 'deleted', name='user_status_enum'), server_default='active', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('bans',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Enum('spam', 'harassment', 'fake_profile', 'inappropriate_content', 'underage', 'scam', 'other', name='ban_reason_enum'), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lift_comment', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bans'))
    )
    op.create_index(op.f('ix_bans_user_id'), 'bans', ['user_id'], unique=True, postgresql_where=sa.text('lifted_at IS NULL'))
    op.create_index(op.f('ix_bans_user_id_created_at'), 'bans', ['user_id', 'created_at'], unique=False)
    op.create_table('reactions',
    sa.Column('from_user_id', sa.BigInteger(), nullable=False),
    sa.Column('to_user_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Enum('like', 'dislike', name='reaction_action_enum'), nullable=False),
    sa.Column('is_super', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("is_super IS false OR action = 'like'", name=op.f('ck_reactions_super_only_on_like')),
    sa.CheckConstraint("message IS NULL OR action = 'like'", name=op.f('ck_reactions_message_only_on_like')),
    sa.CheckConstraint('from_user_id != to_user_id', name=op.f('ck_reactions_not_self')),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_reactions_from_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_reactions_to_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reactions')),
    sa.UniqueConstraint('from_user_id', 'to_user_id', name='uq_reaction_pair')
    )
    op.create_index(op.f('ix_reactions_from_user_id'), 'reactions', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_reactions_to_user_id'), 'reactions', ['to_user_id'], unique=False)
    op.create_table('reports',
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Enum('spam', 'harassment', 'fake_profile', 'inappropriate_content', 'underage', 'scam', 'other', name='report_reason_enum'), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', 'dismissed', name='report_status_enum'), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('reporter_id != target_id', name=op.f('ck_reports_not_self')),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], name=op.f('fk_reports_target_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_status_created_at'), 'reports', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_target_id'), 'reports', ['target_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('min_age', sa.SmallInteger(), server_default='18', nullable=False),
    sa.Column('max_age', sa.SmallInteger(), server_default='100', nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='user_profile_gender_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('min_age <= max_age', name=op.f('ck_user_preferences_age_range')),
    sa.CheckConstraint('min_age >= 18 AND max_age <= 100', name=op.f('ck_user_preferences_age_bounds')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_preferences_user_id'))
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='user_profile_gender_enum'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_index('ix_user_profiles_discovery', 'user_profiles', ['gender', 'birth_date'], unique=False, postgresql_where=sa.text('is_visible IS true'))
    op.create_table('user_telegrams',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=True),
    sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_telegrams_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_telegrams')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_user_telegrams_telegram_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_telegrams_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_telegrams')
    op.drop_index('ix_user_profiles_discovery', table_name='user_profiles', postgresql_where=sa.text('is_visible IS true'))
    op.drop_table('user_profiles')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_reports_target_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status_created_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_reactions_to_user_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_from_user_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_bans_user_id_created_at'), table_name='bans')
    op.drop_index(op.f('ix_bans_user_id'), table_name='bans', postgresql_where=sa.text('lifted_at IS NULL'))
    op.drop_table('bans')
    op.drop_table('users')
    # ### end Alembic commands ###
