"""complete profile fields

Revision ID: 9ab8585b215e
Revises: 267efcacd90f
Create Date: 2026-09-29 16:04:34.047207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ab8585b215e'
down_revision: Union[str, Sequence[str], None] = '267efcacd90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('relationship', 'friendship', 'casual', 'chatting', name='dating_goal_enum').create(op.get_bind())
    op.add_column('user_preferences', sa.Column('city_id', sa.BigInteger(), nullable=True))
    op.add_column('user_preferences', sa.Column('dating_goal', postgresql.ENUM('relationship', 'friendship', 'casual', 'chatting', name='dating_goal_enum', create_type=False), nullable=True))
    op.create_foreign_key(op.f('fk_user_preferences_city_id_cities'), 'user_preferences', 'cities', ['city_id'], ['id'])
    op.add_column('user_profiles', sa.Column('city_id', sa.BigInteger(), nullable=False))
    op.add_column('user_profiles', sa.Column('dating_goal', postgresql.ENUM('relationship', 'friendship', 'casual', 'chatting', name='dating_goal_enum', create_type=False), nullable=False))
    op.alter_column('user_profiles', 'bio',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=True)
    op.drop_index(op.f('ix_user_profiles_discovery'), table_name='user_profiles', postgresql_where='(is_visible IS TRUE)')
    op.create_foreign_key(op.f('fk_user_profiles_city_id_cities'), 'user_profiles', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###
    # Appended by hand: autogenerate does not detect check constraints on an
    # existing table (docs/architecture/conventions.md → Migrations).
    op.create_check_constraint(op.f('ck_user_profiles_bio_not_empty'), 'user_profiles', "bio IS NULL OR bio <> ''")


def downgrade() -> None:
    """Downgrade schema."""
    # Appended by hand, see upgrade().
    op.drop_constraint(op.f('ck_user_profiles_bio_not_empty'), 'user_profiles', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_profiles_city_id_cities'), 'user_profiles', type_='foreignkey')
    op.create_index(op.f('ix_user_profiles_discovery'), 'user_profiles', ['gender', 'birth_date'], unique=False, postgresql_where='(is_visible IS TRUE)')
    op.alter_column('user_profiles', 'bio',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('user_profiles', 'dating_goal')
    op.drop_column('user_profiles', 'city_id')
    op.drop_constraint(op.f('fk_user_preferences_city_id_cities'), 'user_preferences', type_='foreignkey')
    op.drop_column('user_preferences', 'dating_goal')
    op.drop_column('user_preferences', 'city_id')
    sa.Enum('relationship', 'friendship', 'casual', 'chatting', name='dating_goal_enum').drop(op.get_bind())
    # ### end Alembic commands ###
