"""align reports and bans

Revision ID: f8ddf72b9147
Revises: 1b08786564b8
Create Date: 2026-09-29 15:43:06.939485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8ddf72b9147'
down_revision: Union[str, Sequence[str], None] = '1b08786564b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bans', 'expires_at')
    op.create_index(op.f('ix_reports_reporter_id_target_id'), 'reports', ['reporter_id', 'target_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_reporter_id_target_id'), table_name='reports', postgresql_where=sa.text("status = 'open'"))
    op.add_column('bans', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
