"""add matches

Revision ID: 1af132892dbc
Revises: 9ab8585b215e
Create Date: 2026-09-29 16:19:05.416126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1af132892dbc'
down_revision: Union[str, Sequence[str], None] = '9ab8585b215e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('user_a_id', sa.BigInteger(), nullable=False),
    sa.Column('user_b_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('user_a_id < user_b_id', name=op.f('ck_matches_ordered_pair')),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], name=op.f('fk_matches_user_a_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], name=op.f('fk_matches_user_b_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('user_a_id', 'user_b_id', name='uq_match_pair')
    )
    op.create_index(op.f('ix_matches_user_b_id'), 'matches', ['user_b_id'], unique=False)
    op.drop_index(op.f('ix_reactions_from_user_id'), table_name='reactions')
    op.create_index(op.f('ix_reactions_from_user_id_action_is_super_created_at'), 'reactions', ['from_user_id', 'action', 'is_super', 'created_at'], unique=False)
    # ### end Alembic commands ###
    # Appended by hand: autogenerate does not detect check constraints on an
    # existing table (docs/architecture/conventions.md → Migrations).
    op.create_check_constraint(op.f('ck_reactions_message_not_empty'), 'reactions', "message IS NULL OR message <> ''")


def downgrade() -> None:
    """Downgrade schema."""
    # Appended by hand, see upgrade().
    op.drop_constraint(op.f('ck_reactions_message_not_empty'), 'reactions', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reactions_from_user_id_action_is_super_created_at'), table_name='reactions')
    op.create_index(op.f('ix_reactions_from_user_id'), 'reactions', ['from_user_id'], unique=False)
    op.drop_index(op.f('ix_matches_user_b_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
