"""add regions and cities

Revision ID: 267efcacd90f
Revises: f8ddf72b9147
Create Date: 2026-09-29 15:54:57.214090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '267efcacd90f'
down_revision: Union[str, Sequence[str], None] = 'f8ddf72b9147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('O', 'K', name='region_code_type_enum').create(op.get_bind())
    op.create_table('regions',
    sa.Column('katotth_code', sa.String(length=19), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('code_type', postgresql.ENUM('O', 'K', name='region_code_type_enum', create_type=False), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('katotth_code', name=op.f('uq_regions_katotth_code'))
    )
    op.create_table('cities',
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('katotth_code', sa.String(length=19), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_cities_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('katotth_code', name=op.f('uq_cities_katotth_code'))
    )
    op.create_index(op.f('ix_cities_region_id'), 'cities', ['region_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_region_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_table('regions')
    sa.Enum('O', 'K', name='region_code_type_enum').drop(op.get_bind())
    # ### end Alembic commands ###
